export interface Service {
  id: string
  slug: string
  name: string
  category: string
  tagline: string
  description: string
  longDescription: string
  icon: string
  heroImage: string
  gallery: string[]
  features: string[]
  startingPrice: number
  featured: boolean
}

export const SERVICES: Service[] = [
  {
    id: '1',
    slug: 'wedding-decoration',
    name: 'Wedding Decoration',
    category: 'Wedding',
    tagline: 'Where Forever Begins',
    description: 'Transform your wedding into a breathtaking fairy-tale with our bespoke decoration services.',
    longDescription: 'Our wedding decoration team creates immersive environments that reflect the unique love story of each couple. From ethereal floral installations to dramatic mandap designs, every element is curated with precision and artistry. We specialize in both traditional South Indian weddings and modern fusion celebrations.',
    icon: 'Heart',
    heroImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1545232979-fbfd42e000b5?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Floral Mandap Design', 'Stage & Backdrop', 'Table Centrepieces', 'Aisle Décor', 'Entry Arch', 'Fairy Light Canopy', 'Floral Photo Wall', 'Bridal Suite Setup'],
    startingPrice: 75000,
    featured: true,
  },
  {
    id: '2',
    slug: 'engagement',
    name: 'Engagement',
    category: 'Wedding',
    tagline: 'A Promise of Eternity',
    description: 'Celebrate your engagement with elegant and romantic decorations that set the perfect tone.',
    longDescription: 'Your engagement is the beginning of your forever. We create magical settings that celebrate this milestone with sophistication and romance. Our engagement packages include customised floral setups, ambient lighting, and personalised touches that make the occasion unforgettable.',
    icon: 'Gem',
    heroImage: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Floral Ring Setup', 'Photo Backdrop', 'Table Settings', 'Balloon Décor', 'Champagne Setup', 'Mood Lighting'],
    startingPrice: 35000,
    featured: true,
  },
  {
    id: '3',
    slug: 'reception',
    name: 'Reception',
    category: 'Wedding',
    tagline: 'Grand Celebrations Await',
    description: 'Host a spectacular reception that your guests will remember for a lifetime.',
    longDescription: 'The reception is your opportunity to celebrate with everyone who matters. We create grand, immersive environments with dramatic stage setups, lush floral arrangements, and stunning lighting that transforms any venue into a palace.',
    icon: 'Star',
    heroImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Grand Stage Setup', 'Welcome Entry Arch', 'Round Table Décor', 'Candle Lighting', 'Dance Floor Design', 'Buffet Styling'],
    startingPrice: 85000,
    featured: false,
  },
  {
    id: '4',
    slug: 'birthday-decoration',
    name: 'Birthday Decoration',
    category: 'Celebration',
    tagline: 'Make Every Year Magical',
    description: 'From intimate gatherings to grand milestone celebrations, we create the perfect birthday setup.',
    longDescription: 'Every birthday deserves to be extraordinary. Whether it\'s a first birthday bash or a lavish milestone celebration, our team designs stunning birthday setups with themed décor, balloon artistry, and personalised touches.',
    icon: 'Cake',
    heroImage: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1531956531700-dc024130f85d?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Theme Decoration', 'Balloon Arches', 'Photo Booth', 'Cake Table Setup', 'LED Signage', 'Confetti Shower'],
    startingPrice: 15000,
    featured: true,
  },
  {
    id: '5',
    slug: 'baby-shower',
    name: 'Baby Shower',
    category: 'Celebration',
    tagline: 'Welcome Your Little Star',
    description: 'Celebrate the arrival of your little one with sweet and dreamy baby shower decorations.',
    longDescription: 'A baby shower is one of life\'s most precious moments. Our baby shower setups are soft, dreamy, and delightfully personalised — from pastel balloon installations to themed dessert tables and gender reveal moments.',
    icon: 'Baby',
    heroImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Theme Setup', 'Balloon Garlands', 'Dessert Table', 'Photo Backdrop', 'Gift Table', 'Floral Arrangements'],
    startingPrice: 20000,
    featured: false,
  },
  {
    id: '6',
    slug: 'stage-decoration',
    name: 'Stage Decoration',
    category: 'Decoration',
    tagline: 'Centre Stage, Always',
    description: 'Dramatic, breathtaking stage designs that create powerful first impressions.',
    longDescription: 'The stage is the focal point of any event. Our stage decoration team creates dramatic backdrops using floral walls, fabric draping, LED installations, and custom props that command attention and create stunning photo opportunities.',
    icon: 'Sparkles',
    heroImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Floral Backdrop', 'Fabric Draping', 'LED Wall', 'Custom Signage', 'Prop Design', 'Lighting Design'],
    startingPrice: 25000,
    featured: false,
  },
  {
    id: '7',
    slug: 'theme-decoration',
    name: 'Theme Decoration',
    category: 'Decoration',
    tagline: 'Bring Your Vision to Life',
    description: 'Immersive themed event environments that transport your guests to another world.',
    longDescription: 'Theme decoration is where imagination meets execution. Our creative team specialises in crafting fully immersive themed environments — from tropical paradise to Bollywood glam, Rajasthani royalty to futuristic galaxy — every element curated to perfection.',
    icon: 'Palette',
    heroImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Custom Theme Design', 'Full Venue Transformation', 'Prop Creation', 'Themed Costumes', 'Entry Experience', 'Themed Catering Setup'],
    startingPrice: 45000,
    featured: true,
  },
  {
    id: '8',
    slug: 'corporate-events',
    name: 'Corporate Events',
    category: 'Corporate',
    tagline: 'Excellence Meets Elegance',
    description: 'Professional corporate event management that elevates your brand and impresses stakeholders.',
    longDescription: 'Corporate events are a reflection of your brand. We manage everything from product launches and annual days to team outings and award ceremonies. Our corporate event team ensures seamless execution with professional décor, AV setup, and coordinated logistics.',
    icon: 'Briefcase',
    heroImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Branding & Signage', 'Stage & AV', 'Conference Setup', 'Award Ceremony', 'Gala Dinner', 'Product Launch'],
    startingPrice: 100000,
    featured: false,
  },
  {
    id: '9',
    slug: 'school-events',
    name: 'School Events',
    category: 'Education',
    tagline: 'Celebrate Every Achievement',
    description: 'Creative and vibrant event management for school annual days, fests, and graduation ceremonies.',
    longDescription: 'School events should be inspiring and memorable for students, parents, and faculty alike. We specialise in school annual days, sports days, graduation ceremonies, and cultural fests with colourful décor, stage setups, and event coordination.',
    icon: 'GraduationCap',
    heroImage: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Stage Setup', 'Welcome Arch', 'Seating Arrangement', 'Backdrop Design', 'Certificate Podium', 'Cultural Décor'],
    startingPrice: 30000,
    featured: false,
  },
  {
    id: '10',
    slug: 'college-events',
    name: 'College Events',
    category: 'Education',
    tagline: 'Unforgettable Campus Moments',
    description: 'Dynamic and energetic event management for college fests, farewell parties, and convocations.',
    longDescription: 'College events demand energy, creativity, and precision. From tech fests to cultural nights, farewell parties to graduation ceremonies, our team delivers high-impact setups with trendy décor, professional sound, and memorable experiences.',
    icon: 'University',
    heroImage: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Fest Stage', 'DJ & Sound', 'Sponsor Banners', 'Photo Ops', 'Farewell Setup', 'Convocation Stage'],
    startingPrice: 40000,
    featured: false,
  },
  {
    id: '11',
    slug: 'photography',
    name: 'Photography',
    category: 'Media',
    tagline: 'Moments Frozen in Time',
    description: 'Professional photography that captures the emotion, beauty, and story of every event.',
    longDescription: 'Our photography team consists of award-winning photographers who specialise in event documentation. Using cinema-grade equipment and artistic sensibility, we capture not just moments but emotions, stories, and the authentic essence of your celebration.',
    icon: 'Camera',
    heroImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Candid Photography', 'Portrait Sessions', 'Drone Shots', 'Photo Albums', 'Same-Day Edit', 'Cloud Gallery'],
    startingPrice: 25000,
    featured: true,
  },
  {
    id: '12',
    slug: 'videography',
    name: 'Videography',
    category: 'Media',
    tagline: 'Your Story in Motion',
    description: 'Cinematic wedding and event films that you\'ll treasure for generations.',
    longDescription: 'Our videography team creates cinematic masterpieces that preserve your most precious moments. Using 4K cameras, drones, and professional stabilisation, we craft narrative-driven films with stunning colour grading and emotional storytelling.',
    icon: 'Film',
    heroImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['4K Cinematic Film', 'Drone Coverage', 'Highlights Reel', 'Live Streaming', 'Same-Day Edit', 'Digital Delivery'],
    startingPrice: 35000,
    featured: false,
  },
  {
    id: '13',
    slug: 'dj',
    name: 'DJ',
    category: 'Entertainment',
    tagline: 'Music That Moves You',
    description: 'Professional DJ services that set the perfect mood for every moment of your event.',
    longDescription: 'Our resident DJs are experienced in all genres — from Bollywood to EDM, classical to contemporary. With professional sound equipment and lighting rigs, we ensure the dance floor stays packed and the atmosphere electric throughout your event.',
    icon: 'Music',
    heroImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Professional DJ', 'Premium Sound', 'LED Dance Floor', 'Fog Machine', 'LED Uplighting', 'Custom Playlist'],
    startingPrice: 20000,
    featured: false,
  },
  {
    id: '14',
    slug: 'sound-and-lighting',
    name: 'Sound & Lighting',
    category: 'Technical',
    tagline: 'The Right Atmosphere',
    description: 'State-of-the-art sound systems and dramatic lighting that transform any venue.',
    longDescription: 'Professional sound and lighting can make or break an event. Our technical team uses industry-leading equipment including line arrays, intelligent moving heads, wash lights, and LED systems to create immersive audiovisual experiences.',
    icon: 'Zap',
    heroImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['PA Line Array', 'Moving Head Lights', 'LED Wash', 'Gobo Projection', 'Truss Structure', 'Stage Monitors'],
    startingPrice: 30000,
    featured: false,
  },
  {
    id: '15',
    slug: 'catering',
    name: 'Catering',
    category: 'Food & Beverage',
    tagline: 'Culinary Excellence',
    description: 'Exquisite catering that delights every palate with premium cuisine and impeccable service.',
    longDescription: 'Our catering service is a culinary journey. With expert chefs specialising in South Indian, North Indian, Continental, and fusion cuisines, we create bespoke menus that delight guests and complement your event perfectly. From intimate dinners to banquet spreads.',
    icon: 'ChefHat',
    heroImage: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1555244162-803834f70033?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['South & North Indian Menus', 'Live Cooking Stations', 'Buffet & Plated Service', 'Mocktail Bar', 'Custom Dessert Counter', 'Food Styling'],
    startingPrice: 50000,
    featured: false,
  },
  {
    id: '16',
    slug: 'event-planning',
    name: 'Event Planning',
    category: 'Planning',
    tagline: 'Seamless From Start to Finish',
    description: 'Complete end-to-end event planning and coordination for a stress-free experience.',
    longDescription: 'Let us handle every detail so you can enjoy your event. Our experienced event planners coordinate vendors, manage timelines, handle logistics, and ensure flawless execution. From initial concept to final farewell, we are your dedicated event partners.',
    icon: 'ClipboardList',
    heroImage: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1920&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80&auto=format&fit=crop',
    ],
    features: ['Dedicated Planner', 'Vendor Coordination', 'Timeline Management', 'Budget Planning', 'Day-of Coordination', 'Post-Event Report'],
    startingPrice: 50000,
    featured: false,
  },
]

export const FEATURED_SERVICES = SERVICES.filter(s => s.featured)
export const getServiceBySlug = (slug: string) => SERVICES.find(s => s.slug === slug)
